apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service
  description: A demo service to test PostgreSQL persistence
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
